### ISSUE TITLE
Analysis of possible Javascript libraries for charting.

### ISSUE THREAD

**Issue by pibebtol** [pibebtol/slr-toolkit#6]
There is a multitude of different libraries for charting in Javascript.
This issue (based on current information) will focus primarily on _plotly.js_, _d3_ and _vega_.

**Comment by pibebtol** [comment]
## [plotly.js](https://plot.ly/javascript/)
Library to create graphs and diagrams, heavily based on d3. Free to use and open source, however the export as SVG is [restricted](https://plot.ly/javascript/static-image-export/) to users with a paying subscription. It might still be possible to export the graph in another way (from the canvas).

Pretty restrictive on the configuration options for the graphs. Offers the needed graphs for the SLR-Toolkit by default but it might not be configurable enough at some point, if the requirements enhance or change.

## [vega](https://plot.ly/javascript/)
Powerful library to create different types of charts and graphs. Offers powerful configuration options on a basis of [example charts](https://vega.github.io/vega/examples/).

Should offer the needed possibilities to configure it. As far as I can tell, it is more configurable than plotly and offers a good amount of configuration options.

Also based on d3.

Bar chart is straight forward, bubble chart should be configurable with the given possibilities, maybe based on [scatter plot](https://vega.github.io/vega/examples/scatter-plot/).

## [d3](https://d3js.org/)

Purely configurable and basis for the other two.

Should offer any needed configuration options.

Problem is, that it is really low level and needs a good amount of working into to understand the basis of chart creation.

**Comment by martinmo** [comment]
> Problem is, that it is really high level and needs a good amount of working into to understand the basis of chart creation.

You probably meant "low level"?

So in the end, what's your final candidate? Do you want to go with vega, or do you want to continue looking for other libraries?

**Comment by pibebtol** [comment]
> You probably meant "low level"?

Yes, thank you!

> So in the end, what's your final candidate? Do you want to go with vega, or do you want to continue looking for other libraries?

The chosen candidate is *vega*, for the basic creation of charts with dummy data. 

If I encounter problems on the way, *plotly* should be a good fallback variant.

If the other charting libraries are too high level, we can always switch to *d3* and invest more time into the graphing.
